# Generated by Django 4.0.4 on 2022-06-03 18:52

import clientes.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(default=uuid.UUID('07dca3d2-ef04-4d74-81c8-56f82e513ea4'), max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaVencimiento', models.DateField()),
                ('cuenta', models.EmailField(max_length=254, verbose_name=clientes.models.Cuenta)),
                ('contraseña', models.CharField(max_length=10, verbose_name=clientes.models.Cuenta)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.CharField(default=uuid.UUID('85a9f285-6dc6-480a-b96f-e6862d6348f7'), max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=10)),
            ],
        ),
    ]
