# Generated by Django 4.0.4 on 2022-06-03 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cuenta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.CharField(default=uuid.UUID('a066b59a-2c32-42d8-956a-32a12bc39237'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.CharField(default=uuid.UUID('3afbc1b3-e62c-4fc7-8f88-caf8dab096f5'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
