# Generated by Django 4.0.4 on 2022-06-07 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.CharField(default=uuid.UUID('ca8dbaac-18db-41cf-bde6-62e51c981a20'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id',
            field=models.CharField(default=uuid.UUID('13790cf9-9cdb-44ea-944f-f4d157c89ffd'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='id',
            field=models.CharField(default=uuid.UUID('e0f6d54e-6424-4343-8deb-cc215cedd94e'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
