# Generated by Django 4.0.4 on 2022-06-04 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_contraseña_alter_cliente_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='servicio',
            field=models.CharField(blank=True, choices=[('NETFLIX', 'NETFLIX'), ('AMAZON', 'AMAZON'), ('DISNEY', 'DISNEY')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.CharField(default=uuid.UUID('a091d948-953a-4d82-9edb-251c99be22e4'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.CharField(default=uuid.UUID('b86e2e96-4526-4fc3-8a23-f54519b1b4fc'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
