# Generated by Django 4.0.4 on 2022-06-04 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_servicio_alter_cliente_id_alter_cuenta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='servicio',
            field=models.CharField(blank=True, choices=[('NETFLIX', 'NETFLIX'), ('AMAZON', 'AMAZON'), ('DISNEY', 'DISNEY')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.CharField(default=uuid.UUID('cc6e8d19-c552-4f06-ac9e-a0fcfd441dd6'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.CharField(default=uuid.UUID('a0595969-c309-4404-9161-5e337cafc9b3'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
