# Generated by Django 4.0.4 on 2022-06-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_id_alter_empleados_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='area',
            field=models.CharField(max_length=30),
        ),
    ]
