# Generated by Django 4.0.4 on 2022-06-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_servicios_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
